'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, ArrowRight, Check, CloudUpload, FileCheck2, FileText, Globe2, Link2, ShieldCheck, SkipForward, Sparkles } from 'lucide-react'

const steps = ['Business details', 'Connect GST', 'Language & rules', 'First invoice']
const presetDescriptions: Record<string, string> = {
  'Balanced review': 'A practical mix of automated checks and focused human review.',
  'Strict review': 'Review more exceptions with tighter confidence and duplicate rules.',
  'High confidence': 'Keep the queue small and surface only lower-confidence records.',
}

export default function OnboardingFlow() {
  const router = useRouter()
  const [step, setStep] = useState(0)
  const [details, setDetails] = useState({ name: 'Meridian Design Studio Pvt. Ltd.', gstin: '27AABCU9603R1ZM', state: 'Maharashtra' })
  const [gstConnection, setGstConnection] = useState(false)
  const [language, setLanguage] = useState('English')
  const [preset, setPreset] = useState('Balanced review')
  const [fileName, setFileName] = useState('')
  const [sampleLoaded, setSampleLoaded] = useState(false)
  const [finished, setFinished] = useState(false)
  const gstinValid = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(details.gstin)

  function continueStep() {
    if (step < steps.length - 1) setStep((current) => current + 1)
    else setFinished(true)
  }

  function openDashboard() {
    router.push('/app?tour=1')
  }

  return <main className="flex min-h-screen items-center justify-center bg-[#f7f9f8] px-4 py-8 text-slate-900 sm:px-6">
    <section className="w-full max-w-[780px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_80px_rgba(15,23,42,0.08)]" aria-labelledby="onboarding-heading">
      <div className="border-b border-slate-100 px-5 py-5 sm:px-8 sm:py-6"><div className="flex items-center justify-between"><a href="/app" className="flex items-center gap-2 text-[17px] font-semibold tracking-[-0.04em] text-slate-900"><span className="flex size-8 items-center justify-center rounded-lg bg-teal-800 text-white"><FileText className="size-4" /></span>folio<span className="-ml-2 text-teal-700">.</span></a><span className="text-[10px] font-medium text-slate-400">WORKSPACE SETUP</span></div>
        <div className="mt-6 flex items-center" aria-label={`Step ${step + 1} of ${steps.length}`}>
          {steps.map((label, index) => <div key={label} className="flex min-w-0 flex-1 items-center last:flex-none"><div className="flex items-center gap-2"><span className={`flex size-7 shrink-0 items-center justify-center rounded-full text-[10px] font-semibold ${index < step ? 'bg-teal-800 text-white' : index === step ? 'bg-teal-50 text-teal-900 ring-1 ring-teal-700' : 'bg-slate-100 text-slate-400'}`}>{index < step ? <Check className="size-3.5" /> : index + 1}</span><span className={`hidden text-[10px] font-medium sm:inline ${index === step ? 'text-teal-900' : 'text-slate-400'}`}>{label}</span></div>{index < steps.length - 1 && <span className={`mx-2 h-px min-w-3 flex-1 ${index < step ? 'bg-teal-700' : 'bg-slate-200'}`} />}</div>)}
        </div>
      </div>
      {!finished ? <div className="px-5 py-6 sm:px-8 sm:py-8">
        <div className="mb-6"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-teal-800">Step {step + 1} of {steps.length}</p><h1 id="onboarding-heading" className="mt-1 text-2xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-[28px]">{['Tell us about your business', 'Connect your GST account', 'Make Folio yours', 'Add your first invoice'][step]}</h1><p className="mt-1.5 max-w-xl text-xs leading-5 text-slate-500">{['We use these details to organize your workspace and prepare GST reports.', 'This optional demo step previews where secure GST portal access will be set up.', 'Choose the language and review style that works best for your team.', 'Upload an invoice to begin, or explore the workspace with sample data.'][step]}</p></div>
        {step === 0 && <div className="grid gap-4 sm:grid-cols-2"><label className="text-[11px] font-medium text-slate-600 sm:col-span-2">Legal business name<input required value={details.name} onChange={(event) => setDetails({ ...details, name: event.target.value })} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 px-3 text-xs outline-none focus:border-teal-700 focus:ring-2 focus:ring-teal-700/10" /></label><label className="text-[11px] font-medium text-slate-600">GSTIN<div className="relative"><input required maxLength={15} value={details.gstin} onChange={(event) => setDetails({ ...details, gstin: event.target.value.toUpperCase() })} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 px-3 pr-28 font-mono text-xs uppercase outline-none focus:border-teal-700 focus:ring-2 focus:ring-teal-700/10" /><span className={`absolute right-2 top-1/2 rounded-full px-2 py-1 text-[9px] font-semibold ${gstinValid ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-50 text-rose-700'}`}>{gstinValid ? 'Format valid' : 'Check GSTIN'}</span></div></label><label className="text-[11px] font-medium text-slate-600">State<select value={details.state} onChange={(event) => setDetails({ ...details, state: event.target.value })} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs text-slate-700"><option>Maharashtra</option><option>Karnataka</option><option>Delhi</option><option>Tamil Nadu</option><option>Gujarat</option></select></label><p className="text-[10px] text-slate-400 sm:col-span-2">You can update these details later in Business profile settings.</p></div>}
        {step === 1 && <div className="rounded-xl border border-slate-200 bg-slate-50/60 p-5 sm:p-6"><div className="flex flex-col items-start gap-4 sm:flex-row sm:items-center"><span className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-white text-teal-800 shadow-sm"><Link2 className="size-5" /></span><div className="flex-1"><p className="text-sm font-semibold text-slate-900">GST Portal access</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Connect securely to bring in GSTR data and prepare reconciliations. This preview will not request credentials or contact the portal.</p></div><button type="button" onClick={() => setGstConnection((connected) => !connected)} className={`inline-flex h-9 items-center gap-2 rounded-lg px-3 text-[11px] font-semibold ${gstConnection ? 'border border-teal-200 bg-teal-50 text-teal-900' : 'bg-teal-800 text-white hover:bg-teal-900'}`}>{gstConnection ? <><Check className="size-3.5" />Demo connected</> : 'Connect GST portal'}</button></div><div className="mt-4 flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-[10px] text-slate-500"><ShieldCheck className="size-3.5 text-teal-800" />Your credentials are never collected in this preview.</div></div>}
        {step === 2 && <div className="grid gap-5 sm:grid-cols-2"><fieldset className="rounded-xl border border-slate-200 p-4"><legend className="px-1 text-xs font-semibold text-slate-800">Workspace language</legend><div className="mt-2 flex flex-col gap-2">{['English', 'हिन्दी', 'मराठी'].map((option) => <label key={option} className={`flex cursor-pointer items-center gap-2.5 rounded-lg border px-3 py-2.5 text-xs ${language === option ? 'border-teal-300 bg-teal-50/60 text-teal-900' : 'border-slate-200 text-slate-600'}`}><input type="radio" name="language" value={option} checked={language === option} onChange={() => setLanguage(option)} className="accent-teal-800" />{option}</label>)}</div></fieldset><fieldset className="rounded-xl border border-slate-200 p-4"><legend className="px-1 text-xs font-semibold text-slate-800">Validation preset</legend><div className="mt-2 flex flex-col gap-2">{Object.keys(presetDescriptions).map((option) => <label key={option} className={`flex cursor-pointer items-start gap-2.5 rounded-lg border px-3 py-2.5 ${preset === option ? 'border-teal-300 bg-teal-50/60' : 'border-slate-200'}`}><input type="radio" name="preset" value={option} checked={preset === option} onChange={() => setPreset(option)} className="mt-0.5 accent-teal-800" /><span><span className="block text-[11px] font-semibold text-slate-800">{option}</span><span className="mt-0.5 block text-[9px] leading-4 text-slate-500">{presetDescriptions[option]}</span></span></label>)}</div></fieldset><p className="flex items-center gap-2 text-[10px] text-slate-400 sm:col-span-2"><Globe2 className="size-3.5" />You can fine-tune these preferences in settings at any time.</p></div>}
        {step === 3 && <div className="grid gap-3 sm:grid-cols-2"><label className={`flex min-h-[180px] cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed p-5 text-center transition ${fileName ? 'border-teal-300 bg-teal-50/40' : 'border-slate-200 hover:border-teal-300 hover:bg-teal-50/30'}`}><input type="file" accept=".pdf,image/png,image/jpeg" className="sr-only" onChange={(event) => { setFileName(event.target.files?.[0]?.name ?? ''); setSampleLoaded(false) }} /><span className="flex size-11 items-center justify-center rounded-xl bg-white text-teal-800 shadow-sm"><CloudUpload className="size-5" /></span><span className="mt-3 text-xs font-semibold text-slate-800">{fileName || 'Choose an invoice to upload'}</span><span className="mt-1 text-[10px] text-slate-500">PDF, PNG, or JPG · demo only, file stays in this browser</span></label><button type="button" onClick={() => { setSampleLoaded(true); setFileName('') }} className={`flex min-h-[180px] flex-col items-center justify-center rounded-xl border p-5 text-center transition ${sampleLoaded ? 'border-teal-300 bg-teal-50/40' : 'border-slate-200 hover:border-teal-300 hover:bg-teal-50/30'}`}><span className="flex size-11 items-center justify-center rounded-xl bg-white text-slate-600 shadow-sm"><FileCheck2 className="size-5" /></span><span className="mt-3 text-xs font-semibold text-slate-800">Load sample data</span><span className="mt-1 text-[10px] text-slate-500">Explore with a ready-to-review sample invoice.</span>{sampleLoaded && <span className="mt-2 inline-flex items-center gap-1 text-[10px] font-semibold text-teal-800"><Check className="size-3" />Sample selected</span>}</button><p className="text-[10px] text-slate-400 sm:col-span-2">{fileName ? 'The selected file is not uploaded to a server in this preview.' : 'You can also skip this step and add invoices from the workspace later.'}</p></div>}
        <div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-4"><button type="button" onClick={() => setStep((current) => Math.max(current - 1, 0))} disabled={step === 0} className="inline-flex h-9 items-center gap-2 rounded-lg px-3 text-xs font-medium text-slate-600 hover:bg-slate-100 disabled:invisible"><ArrowLeft className="size-3.5" />Back</button><div className="flex items-center gap-2">{step === 1 && <button type="button" onClick={continueStep} className="inline-flex h-9 items-center gap-1.5 rounded-lg px-3 text-xs font-medium text-slate-500 hover:bg-slate-100"><SkipForward className="size-3.5" />Skip</button>}{step === 3 && !fileName && !sampleLoaded && <button type="button" onClick={() => setFinished(true)} className="inline-flex h-9 items-center gap-1.5 rounded-lg px-3 text-xs font-medium text-slate-500 hover:bg-slate-100">Skip for now<SkipForward className="size-3.5" /></button>}<button type="button" onClick={continueStep} disabled={step === 0 && (!details.name.trim() || !gstinValid)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-teal-800 px-4 text-xs font-semibold text-white hover:bg-teal-900 disabled:cursor-not-allowed disabled:opacity-40">{step === steps.length - 1 ? 'Finish setup' : 'Continue'}<ArrowRight className="size-3.5" /></button></div></div>
      </div> : <div className="relative overflow-hidden px-5 py-12 text-center sm:px-8 sm:py-16"><div aria-hidden="true" className="pointer-events-none absolute inset-0 overflow-hidden">{Array.from({ length: 22 }, (_, index) => <span key={index} className="absolute top-0 h-3 w-1.5 animate-[confetti-fall_2.4s_ease-in_forwards] rounded-sm" style={{ left: `${(index * 37) % 100}%`, backgroundColor: ['#0f766e', '#f59e0b', '#38bdf8', '#a78bfa'][index % 4], transform: `rotate(${index * 31}deg)`, animationDelay: `${(index % 7) * 90}ms` }} />)}</div><span className="relative mx-auto flex size-14 items-center justify-center rounded-2xl bg-teal-50 text-teal-800"><Sparkles className="size-6" /></span><p className="relative mt-5 text-[10px] font-semibold uppercase tracking-[0.16em] text-teal-800">You&apos;re all set</p><h1 id="onboarding-heading" className="relative mt-1 text-2xl font-semibold tracking-[-0.04em] text-slate-950">Your workspace is ready.</h1><p className="relative mx-auto mt-2 max-w-md text-xs leading-5 text-slate-500">{details.name} is set up with {language} and the {preset.toLowerCase()} review preset. Take a quick tour to see the key parts of Folio.</p><button type="button" onClick={openDashboard} className="relative mt-6 inline-flex h-10 items-center gap-2 rounded-lg bg-teal-800 px-4 text-xs font-semibold text-white hover:bg-teal-900">Open your dashboard<ArrowRight className="size-3.5" /></button></div>}
    </section>
    <style jsx>{`@keyframes confetti-fall { 0% { transform: translateY(-8px) rotate(0deg); opacity: 0 } 12% { opacity: 1 } 100% { transform: translateY(260px) rotate(260deg); opacity: 0 } }`}</style>
  </main>
}
