'use client'

import { useRouter } from 'next/navigation'
import { ArrowRight, ArrowUpRight, BadgeCheck, CalendarDays, CircleAlert, FileCheck2, FileText, Plus, UploadCloud, Users, X } from 'lucide-react'
import { AppShell, MetricCard, PageHeading, SectionCard, formatRupees } from '@/components/app-shell'

const tourCopy = [
  { title: 'Your workspace navigation', text: 'Move between invoices, reconciliation, vendors, and reports from this sidebar.' },
  { title: 'Upload your first invoice', text: 'Add an invoice here to extract its key fields and start validation.' },
  { title: 'Review ITC exposure', text: 'Track matched credit and review exceptions before you file.' },
]

export default function OverviewWorkspace({ showTour, initialTourStep = 0 }: { showTour: boolean; initialTourStep?: number }) {
  const router = useRouter()
  const currentTourStep = Math.min(Math.max(initialTourStep, 0), tourCopy.length - 1)
  const tourTarget = currentTourStep === 0 ? 'sidebar' : currentTourStep === 1 ? 'upload' : 'itc'

  function closeTour() {
    router.replace('/app', { scroll: false })
  }

  function nextTourStep() {
    if (currentTourStep >= tourCopy.length - 1) closeTour()
    else router.replace(`/app?tour=1&tourStep=${currentTourStep + 1}`, { scroll: false })
  }

  return <AppShell active="Overview" tourTarget={showTour ? tourTarget : undefined}>
    <PageHeading eyebrow="Overview" title="Good morning, Aditi" description="Here&apos;s where your GST workspace stands for April 2026." action={<a id="tour-upload" href="/app/upload" className={`inline-flex h-9 w-fit items-center gap-2 rounded-lg bg-[#f8f7e2] px-4 text-sm font-bold text-[#474c80] shadow-sm transition hover:bg-white ${showTour && currentTourStep === 1 ? 'relative z-[61] ring-4 ring-teal-300 ring-offset-4 ring-offset-white' : ''}`}><UploadCloud className="size-4" />Upload invoice</a>} />
    <div className="mb-7 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#d9d9ee] bg-[#e7e6f2] px-5 py-4"><div><p className="text-sm font-bold text-[#393d68]">April close · 2026</p><p className="mt-1 text-sm text-[#686b86]">Your GST workspace is organized and ready for the next filing cycle.</p></div><span className="rounded-full bg-[#474c80] px-4 py-2 text-sm font-bold text-[#f8f7e2]">Period active</span></div>
    <div className="mb-7 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Invoices this month" value="48" note="12 added this week" icon={FileText} /><MetricCard label="ITC ready to claim" value={formatRupees(284200)} note="45 invoices matched" icon={FileCheck2} /><MetricCard label="Need your review" value="6" note="2 high priority" icon={CircleAlert} /><MetricCard label="Active vendors" value="32" note="4 new this month" icon={Users} /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,0.8fr)]">
      <SectionCard title="Filing health" description="April 2026 · GSTR-3B preparation" >
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative flex size-40 shrink-0 items-center justify-center rounded-full" style={{ background: 'conic-gradient(#474c80 0deg 338deg, #dedecb 338deg 360deg)' }} role="img" aria-label="Filing health: 94 percent"><div className="flex size-[132px] flex-col items-center justify-center rounded-full bg-[#fffef4]"><strong className="text-4xl font-bold tracking-tight text-[#393d68]">94%</strong><span className="text-sm font-semibold text-[#686b86]">ready</span></div></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">Looking good so far</p><p className="mt-1 text-[11px] leading-5 text-slate-500">45 of 48 invoices are matched to GSTR-2B. Clear 3 remaining items to get filing-ready.</p></div><BadgeCheck className="hidden size-5 shrink-0 text-teal-700 sm:block" /></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-lg bg-emerald-50 p-2.5"><span className="block text-[9px] text-emerald-800">Matched</span><strong className="mt-0.5 block text-sm text-emerald-900">45</strong></div><div className="rounded-lg bg-amber-50 p-2.5"><span className="block text-[9px] text-amber-800">Review</span><strong className="mt-0.5 block text-sm text-amber-900">6</strong></div><div className="rounded-lg bg-slate-50 p-2.5"><span className="block text-[9px] text-slate-600">Pending</span><strong className="mt-0.5 block text-sm text-slate-800">3</strong></div></div></div></div>
        <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><p className="flex items-center gap-1.5 text-[10px] text-slate-500"><CalendarDays className="size-3.5" />Next filing due <strong className="font-semibold text-slate-800">20 May 2026</strong></p><a href="/app/itc" className="inline-flex items-center gap-1 text-[10px] font-semibold text-teal-800 hover:text-teal-950">View reconciliation<ArrowRight className="size-3" /></a></div>
      </SectionCard>
      <SectionCard title="Review queue" description="A few quick checks to keep your books clean."><div className="flex flex-col divide-y divide-slate-100">{[
        { id: 'INV-2026-0418', vendor: 'Northstar Supplies', note: 'Taxable value differs by INR 500', tone: 'bg-amber-50 text-amber-800' },
        { id: 'INV-2026-0392', vendor: 'Aster Office Mart', note: 'GSTIN needs a quick check', tone: 'bg-rose-50 text-rose-800' },
        { id: 'INV-2026-0355', vendor: 'Kaveri Components', note: 'Ready for approval', tone: 'bg-emerald-50 text-emerald-800' },
      ].map((item) => <a key={item.id} href="/app/invoices" className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className={`flex size-8 shrink-0 items-center justify-center rounded-lg ${item.tone}`}><FileText className="size-3.5" /></span><span className="min-w-0 flex-1"><span className="block truncate text-[11px] font-semibold text-slate-800">{item.vendor}</span><span className="block truncate text-[10px] text-slate-500">{item.id} · {item.note}</span></span><ArrowUpRight className="size-3.5 text-slate-400" /></a>)}</div><a href="/app/invoices" className="mt-4 flex h-8 items-center justify-center rounded-lg border border-slate-200 text-[10px] font-semibold text-slate-600 hover:bg-slate-50">Open review queue</a></SectionCard>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,0.8fr)]">
      <section id="tour-itc" className={`relative rounded-xl ${showTour && currentTourStep === 2 ? 'z-[61] rounded-xl ring-4 ring-teal-300 ring-offset-4 ring-offset-white' : ''}`}><SectionCard title="ITC snapshot" description="Input tax credit across your purchase register."><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-slate-100 p-3"><span className="text-[10px] text-slate-500">Eligible</span><strong className="mt-1 block text-lg font-semibold text-slate-900">INR 2.84L</strong><span className="mt-1 block text-[9px] text-emerald-700">+8.4% from March</span></div><div className="rounded-lg border border-slate-100 p-3"><span className="text-[10px] text-slate-500">Pending match</span><strong className="mt-1 block text-lg font-semibold text-slate-900">INR 18,400</strong><span className="mt-1 block text-[9px] text-amber-700">3 invoices</span></div><div className="rounded-lg border border-slate-100 p-3"><span className="text-[10px] text-slate-500">At risk</span><strong className="mt-1 block text-lg font-semibold text-slate-900">INR 6,250</strong><span className="mt-1 block text-[9px] text-rose-700">2 exceptions</span></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-700" style={{ width: '84%' }} /></div><div className="mt-2 flex justify-between text-[9px] text-slate-400"><span>84% of purchase value reconciled</span><a href="/app/itc" className="font-semibold text-teal-800">Open ITC report</a></div></SectionCard></section>
      <SectionCard title="Recent activity" description="Latest activity across your workspace."><div className="flex flex-col gap-3">{[
        ['Aditi Mehta', 'reviewed an invoice field', '10 min ago', 'AM'],
        ['System', 'matched 4 invoices to GSTR-2B', '1 hour ago', 'SY'],
        ['Rohan Shah', 'sent a vendor follow-up', 'Yesterday', 'RS'],
      ].map(([name, action, time, initials]) => <div key={`${name}-${action}`} className="flex items-center gap-2.5"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-slate-100 text-[9px] font-semibold text-slate-600">{initials}</span><span className="min-w-0 flex-1 text-[10px] text-slate-600"><strong className="font-semibold text-slate-800">{name}</strong> {action}</span><span className="shrink-0 text-[9px] text-slate-400">{time}</span></div>)}</div><a href="/app/reports" className="mt-4 inline-flex items-center gap-1 text-[10px] font-semibold text-teal-800">Open audit trail<ArrowRight className="size-3" /></a></SectionCard>
    </div>
    <div className="mt-6 grid gap-4 md:grid-cols-3"><a href="/app/invoices" className="group rounded-2xl border border-[#dedecb] bg-[#fffef4] p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><span className="flex size-11 items-center justify-center rounded-xl bg-[#e7e6f2] text-[#474c80]"><FileText className="size-5" /></span><p className="mt-4 text-lg font-bold text-[#393d68]">Invoice register</p><p className="mt-1 text-sm leading-6 text-[#686b86]">Find, sort, and review every submitted invoice in one searchable workspace.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#474c80]">Explore invoices<ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></a><a href="/app/vendors" className="group rounded-2xl border border-[#dedecb] bg-[#fffef4] p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><span className="flex size-11 items-center justify-center rounded-xl bg-[#e0eee5] text-[#28735f]"><Users className="size-5" /></span><p className="mt-4 text-lg font-bold text-[#393d68]">Vendor network</p><p className="mt-1 text-sm leading-6 text-[#686b86]">Keep GSTINs, transaction trends, and supplier health close at hand.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#28735f]">Browse vendors<ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></a><a href="/app/reports" className="group rounded-2xl border border-[#dedecb] bg-[#fffef4] p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><span className="flex size-11 items-center justify-center rounded-xl bg-[#f3e7cd] text-[#896329]"><CalendarDays className="size-5" /></span><p className="mt-4 text-lg font-bold text-[#393d68]">Reports & audit</p><p className="mt-1 text-sm leading-6 text-[#686b86]">Get a richer view of filing health, reconciliation, and workspace activity.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#896329]">Explore reports<ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></a></div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#c9dccc] bg-[#e5efe4] p-5"><div><p className="text-base font-bold text-[#355d4d]">Make Folio yours</p><p className="mt-1 text-sm text-[#526d5d]">Set up your business profile and choose how invoices should be reviewed.</p></div><a href="/app/onboarding" className="inline-flex h-11 items-center gap-2 rounded-xl border border-[#b7ceb9] bg-[#fffef4] px-4 text-sm font-bold text-[#355d4d] hover:bg-white"><Plus className="size-4" />Run setup again</a></div>
    {showTour && <><div className="fixed inset-0 z-[60] bg-slate-950/45" aria-hidden="true" /><section role="dialog" aria-modal="true" aria-labelledby="tour-title" className="fixed inset-x-4 bottom-5 z-[70] mx-auto max-w-md rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl sm:bottom-8"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-teal-800">Product tour · {currentTourStep + 1} of {tourCopy.length}</p><h2 id="tour-title" className="mt-1 text-sm font-semibold text-slate-900">{tourCopy[currentTourStep].title}</h2><p className="mt-1.5 text-xs leading-5 text-slate-500">{tourCopy[currentTourStep].text}</p></div><button type="button" onClick={closeTour} aria-label="Close product tour" className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100"><X className="size-4" /></button></div><div className="mt-4 flex items-center justify-between"><button type="button" onClick={closeTour} className="text-[10px] font-medium text-slate-500 hover:text-slate-800">Skip tour</button><button type="button" onClick={nextTourStep} className="inline-flex h-8 items-center gap-1.5 rounded-lg bg-teal-800 px-3 text-[10px] font-semibold text-white hover:bg-teal-900">{currentTourStep === tourCopy.length - 1 ? 'Finish tour' : 'Next'}<ArrowRight className="size-3.5" /></button></div></section></>}
  </AppShell>
}
